CREATE TABLE dbo.AI_Knowledge_Base (
    ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    EventID UNIQUEIDENTIFIER NOT NULL,
    CategoryID UNIQUEIDENTIFIER DEFAULT NULL,
    QuestionPattern NVARCHAR(MAX) NOT NULL,
    StandardAnswer NVARCHAR(MAX) NOT NULL,
    MentorID UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_AI_KB_Event FOREIGN KEY (EventID) REFERENCES dbo.Events(EventID) ON DELETE CASCADE,
    CONSTRAINT FK_AI_KB_Category FOREIGN KEY (CategoryID) REFERENCES dbo.Categories(CategoryID),
    CONSTRAINT FK_AI_KB_Mentor FOREIGN KEY (MentorID) REFERENCES dbo.Users(UserID)
);

CREATE INDEX IX_AI_KB_Event ON dbo.AI_Knowledge_Base(EventID);
CREATE INDEX IX_AI_KB_Category ON dbo.AI_Knowledge_Base(CategoryID);
GO
