CREATE TABLE TeamMentorNotes (
    NoteID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TeamID UNIQUEIDENTIFIER NOT NULL,
    MentorID UNIQUEIDENTIFIER NOT NULL,
    Note NVARCHAR(MAX),
    CreatedAt DATETIME2 DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME2,
    
    CONSTRAINT FK_TeamMentorNotes_Teams FOREIGN KEY (TeamID) REFERENCES Teams(TeamID),
    CONSTRAINT FK_TeamMentorNotes_Users FOREIGN KEY (MentorID) REFERENCES Users(UserID),
    CONSTRAINT UQ_TeamMentorNotes_Team_Mentor UNIQUE (TeamID, MentorID)
);
GO
