CREATE TABLE TeamMilestones (
    MilestoneID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TeamID UNIQUEIDENTIFIER NOT NULL,
    MentorUserID UNIQUEIDENTIFIER NOT NULL,
    Label NVARCHAR(255) NOT NULL,
    IsDone BIT NOT NULL DEFAULT 0,
    SortOrder INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME2 NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TeamMilestones_Team FOREIGN KEY (TeamID) REFERENCES Teams(TeamID),
    CONSTRAINT FK_TeamMilestones_Mentor FOREIGN KEY (MentorUserID) REFERENCES Users(UserID)
);
GO
