-- Create Appeals table
CREATE TABLE Appeals (
    AppealID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TeamID UNIQUEIDENTIFIER NOT NULL,
    EventID UNIQUEIDENTIFIER NOT NULL,
    CategoryID UNIQUEIDENTIFIER NOT NULL,
    Title NVARCHAR(255) NOT NULL,
    Reason NVARCHAR(MAX) NOT NULL,
    Status NVARCHAR(50) NOT NULL DEFAULT 'PENDING',
    AppealType NVARCHAR(50) NOT NULL,
    ResolutionNote NVARCHAR(MAX),
    ResolvedByUserID UNIQUEIDENTIFIER,
    CreatedByUserID UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 DEFAULT GETUTCDATE(),
    CONSTRAINT FK_Appeals_Teams FOREIGN KEY (TeamID) REFERENCES Teams(TeamID),
    CONSTRAINT FK_Appeals_Events FOREIGN KEY (EventID) REFERENCES Events(EventID),
    CONSTRAINT FK_Appeals_Categories FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID),
    CONSTRAINT FK_Appeals_ResolvedBy FOREIGN KEY (ResolvedByUserID) REFERENCES Users(UserID),
    CONSTRAINT FK_Appeals_CreatedBy FOREIGN KEY (CreatedByUserID) REFERENCES Users(UserID)
);
GO
