USE SWP_SEAL_HackathonDB;
GO

ALTER TABLE dbo.Events
ALTER COLUMN EventName NVARCHAR(255) NULL;
GO

ALTER TABLE dbo.Events
ALTER COLUMN Description NVARCHAR(MAX) NULL;
GO

ALTER TABLE dbo.Events
ALTER COLUMN Location NVARCHAR(255) NULL;
GO